syn match mines0        /\./
syn match mines1        /1/
syn match mines2        /2/
syn match mines3        /3/
syn match mines4        /4/
syn match mines5        /5/
syn match mines6        /6/
syn match mines7        /7/
syn match mines8        /8/
syn match minesClosed   /#/
syn match minesMine     /\*/
syn match minesQuestion /?/
syn match minesFlag     /!/
